### PR TITLE
vector-tile-spec in Chinese

### PR DESCRIPTION
**Pull request by jingsam**

### CODE REVIEW

**Comment by flippmoke** [comment]
This is awesome, but I have no way to verify or update the text with the specification.

**Comment by jingsam** [comment]
How about @peterqliu ?

**Comment by flippmoke** [comment]
Thanks again for the contribution! We are pleased to have the vector-tile specification translated into other languages. However, we don't have the resources to ensure that spec translations stay in sync with the master version, and therefore we wouldn't want to portray them as normative or official documents by hosting them in this repository. But if you wanted to host this in your own repository, we'd be happy to add a link to the README.

**Comment by jingsam** [comment]
I have send a PR #68

**Pull request closed without merging**
